find_path(FREEIMAGE_INCLUDE_DIRS "FreeImage.h"
	PATHS $ENV{FREEIMAGE_HOME}/Dist/x32)

find_library(FREEIMAGE_LIBRARIES NAMES FreeImage
	PATHS $ENV{FREEIMAGE_HOME}/Dist/x32)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FREEIMAGE DEFAULT_MSG
                                  FREEIMAGE_LIBRARIES FREEIMAGE_INCLUDE_DIRS)

mark_as_advanced(FREEIMAGE_INCLUDE_DIRS FREEIMAGE_LIBRARIES)